feature(heroku): Improve Heroku scripts / docs
Summary:
- Update cookiecutter.json with heroku_slug
- Update cookiecutter.json to derive a valid heroku_slug from
  project_slug
- Update pre_gen_project to check for a valid heroku_slug
- Update app_info.json to use heroku_slug instead of project_slug
- Update README.md with heroku deploy info
- Update README.md to use heroku_slug
- DRY-up Makefile scripts
- Support deploying to 'dev'
- Remove outdated setup doc
- Add new setup doc
- Add gen_secret_key mgmt command
- Delete out of date DEPLOYMENT_NOTES.md
- Add updated heroku-setup.md
- Update .gitignore to ignore cors.json

diff --git a/{{cookiecutter.project_slug}}/Makefile b/{{cookiecutter.project_slug}}/Makefile
--- a/{{cookiecutter.project_slug}}/Makefile
+++ b/{{cookiecutter.project_slug}}/Makefile
@@ -61,36 +61,6 @@ test.js: ## Run Javascript test suite
 	open http://localhost:3000
 	cd django/project/\@static && npm test
 
-{% if cookiecutter.use_heroku.lower() == "y" %}
-.PHONY: heroku.prod.deploy
-heroku.prod.deploy: heroku.build.prod ## Deploy to heroku (prod)
-	docker run --rm -w /usr/app/django \
-		-v ${LOCATION}:/usr/app \
-		--net ${NAME}_default \
-		-e "DJANGO_SETTINGS_MODULE=app.config.settings.prod" \
-		-e "PYTHONPATH=/usr/app/django/project:/usr/app/django/project/vendor" \
-		-e "DEBUG=true" \
-		-it dinopetrone/heroku:latest \
-		fab prod.deploy -f /usr/fabfile
-
-.PHONY: heroku.staging.deploy
-heroku.staging.deploy: heroku.build.prod ## Deploy to heroku (staging)
-	docker run --rm -w /usr/app/django \
-		-v ${LOCATION}:/usr/app \
-		--net ${NAME}_default \
-		-e "DJANGO_SETTINGS_MODULE=app.config.settings.prod" \
-		-e "PYTHONPATH=/usr/app/django/project:/usr/app/django/project/vendor" \
-		-e "DEBUG=true" \
-		-it dinopetrone/heroku:latest \
-		fab staging.deploy -f /usr/fabfile
-
-
-.PHONY: heroku.build.prod
-heroku.build.prod:
-	cd django/project/@static && IS_HEROKU=1 VERSION=$$(git rev-parse HEAD) USE_HTTPS_FOR_ASSETS=$$(heroku config:get USE_HTTPS_FOR_ASSETS) AWS_BUCKET_NAME=$$(heroku config:get AWS_BUCKET_NAME) npm run build
-
-{% endif %}
-
 .PHONY: reqs.git
 reqs.git:
 	-git submodule update --init --remote --recursive
@@ -108,6 +78,63 @@ reqs.node:
 init.django: resetdb
 	docker exec -it ${NAME}_django_1 python manage.py migrate
 	docker exec -it ${NAME}_django_1 python manage.py createsuperuser
+
+{% if cookiecutter.use_heroku.lower() == "y" %}
+# Heroku
+# =====================================
+
+# FAB_CMD_ suffix are lowercase on purpose to ease passing ENV option
+FAB_CMD_dev := fab dev.deploy -f /usr/fabfile
+FAB_CMD_staging := fab staging.deploy -f /usr/fabfile
+FAB_CMD_prod := fab prod.deploy -f /usr/fabfile
+ENV_NAME := dev
+
+# Deploy to Heroku (takes ENV_NAME=<env-name>, see help)
+# AWS_BUCKET_NAME is required for the `collectstatic` run
+# (each env requires it's own s3 buicket, see docs/heroku-setup.md)
+.PHONY: heroku.deploy
+heroku.deploy: heroku.checkenv heroku.assets ## Deploy to Heroku (takes ENV_NAME=<env-name>, see help)
+	docker run --rm -w /usr/app/django \
+		-v ${LOCATION}:/usr/app \
+		--net ${NAME}_default \
+		-e "DJANGO_SETTINGS_MODULE=app.config.settings.prod" \
+		-e "PYTHONPATH=/usr/app/django/project:/usr/app/django/project/vendor" \
+		-e "DEBUG=True" \
+		-e "AWS_BUCKET_NAME=$$(heroku config:get AWS_BUCKET_NAME -r ${ENV_NAME})" \
+		-it dinopetrone/heroku:latest \
+		$(FAB_CMD_$(ENV_NAME))
+
+# Exit if ENV_NAME does not match expected value
+.PHONY: heroku.checkenv
+heroku.checkenv:
+	@if [[ ! $$ENV_NAME == "dev" ]]; then \
+	if [[ ! $$ENV_NAME == "staging" ]]; then \
+	if [[ ! $$ENV_NAME == "prod" ]]; then \
+		echo "Invalid ENV_NAME=${ENV_NAME}, exiting..."; exit 1; \
+	fi \
+	fi \
+	fi
+
+.PHONY: heroku.assets
+heroku.assets:  ## Build Heroku assets (takes ENV_NAME=<env-name>, see help)
+	cd django/project/@static && \
+		IS_HEROKU=1 VERSION=$$(git rev-parse HEAD) \
+		USE_HTTPS_FOR_ASSETS=$$(heroku config:get USE_HTTPS_FOR_ASSETS -r ${ENV_NAME}) \
+		AWS_BUCKET_NAME=$$(heroku config:get AWS_BUCKET_NAME -r ${ENV_NAME}) \
+		npm run build
+
+.PHONY: heroku.shell
+heroku.shell: ## Get a session on the heroku container (takes ENV_NAME=<env-name>, see help)
+	docker run --rm -w /usr/app/django \
+		-v ${LOCATION}:/usr/app \
+		--net ${NAME}_default \
+		-e "DJANGO_SETTINGS_MODULE=app.config.settings.prod" \
+		-e "PYTHONPATH=/usr/app/django/project:/usr/app/django/project/vendor" \
+		-e "DEBUG=True" \
+		-e "AWS_BUCKET_NAME=$$(heroku config:get AWS_BUCKET_NAME -r ${ENV_NAME})" \
+		-it dinopetrone/heroku:latest \
+		/bin/bash
+{% endif %}
 
 # -------------------------------------
 # Makefile Documentation
@@ -131,6 +158,7 @@ help-usage:
 	@echo "make shell"
 	@echo "make po [OPTS=\"...\""]
 	@echo "make mo [OPTS=\"...\""]
+	@echo "make heroku.deploy ENV_NAME=<env-name>"
 
 # Update this target to add additinoal examples
 .PHONY: help-examples
@@ -140,6 +168,8 @@ help-examples:
 	@echo "make shell CONTAINER_NAME=postgres"
 	@echo "make po OPTS=\"-l de -l es\""
 	@echo "make po OPTS=\"-a\""
+	@echo "make heroku.deploy ENV_NAME=dev"
+	@echo "make heroku.deploy ENV_NAME=preview"
 	@echo ""
 
 # -------------------------------------
