fix makefile and deploy scripts, heroku dockerfile

diff --git a/{{cookiecutter.project_slug}}/Makefile b/{{cookiecutter.project_slug}}/Makefile
--- a/{{cookiecutter.project_slug}}/Makefile
+++ b/{{cookiecutter.project_slug}}/Makefile
@@ -90,8 +90,8 @@ init.django: resetdb
 # Heroku Commands
 # =====================================
 
-HEROKU_REMOTE := dev
-HEROKU_SLUG := {{cookiecutter.heroku_slug}}-$(HEROKU_REMOTE)
+ENV_NAME := dev
+APP_NAME := {{cookiecutter.heroku_slug}}-$(ENV_NAME)
 
 .PHONY: heroku.up
 heroku.up: heroku.create heroku.s3 heroku.configure ## Create a Heroku app / remote for this project (see Usage)
@@ -99,7 +99,7 @@ heroku.up: heroku.create heroku.s3 heroku.configure ## Create a Heroku app / rem
 # Create our Heroku app
 .PHONY: heroku.create
 heroku.create:
-	heroku create ${HEROKU_SLUG} -r ${HEROKU_REMOTE}
+	heroku create ${APP_NAME} -r ${ENV_NAME}
 	heroku addons:create heroku-postgresql:hobby-dev
 
 # Set some boilerplate Heroku app configuration
@@ -108,21 +108,37 @@ heroku.configure:
 	heroku config:set DJANGO_SETINGS_MODULE=app.config.settings.prod
 	heroku config:set SECRET_KEY=$$(docker exec -it ${NAME}_django_1 python manage.py gen_secret_key)
 	heroku config:set USE_HTTPS_FOR_ASSETS=1
-	heroku config:set AWS_BUCKET_NAME=${HEROKU_SLUG}
+	heroku config:set AWS_BUCKET_NAME=${APP_NAME}
 	@echo "NOTE: Be sure to set private credentials manually!"
 	@echo "For example:"
 	@echo "     - AWS_ACCESS_KEY_ID"
 	@echo "     - AWS_SECRET_ACCESS_KEY"
 
 # Create an S3 bucket for Heroku app static assets
-# NOTE: Requires that the python aws cli is installed
+# NOTE: Requires that the python aws cli is installed and that you're
+# using the client's profile for the correct environment
 # 	See: http://docs.aws.amazon.com/cli/latest/userguide/installing.html
 .PHONY: heroku.s3
 heroku.s3:
 	wget -O cors.json http://bit.ly/blitzherokus3cors
-	aws s3api create-bucket --bucket ${HEROKU_SLUG}
-	aws s3api put-bucket-cors  --bucket ${HEROKU_SLUG} --cors-configuration file://cors.json
+	aws s3api create-bucket --bucket ${APP_NAME}
+	aws s3api put-bucket-cors  --bucket ${APP_NAME} --cors-configuration file://cors.json
 	-rm -rf cors.json
+
+.PHONY: buildclean
+buildclean:
+	rm -rf django/.build
+
+.PHONY: buildenv
+buildenv: buildclean
+	mkdir django/.build
+	touch django/.build/.env
+	echo "AWS_BUCKET_NAME=$$(heroku config:get AWS_BUCKET_NAME -a ${APP_NAME})" >>  django/.build/.env
+	echo "AWS_ACCESS_KEY_ID=$$(heroku config:get AWS_ACCESS_KEY_ID -a ${APP_NAME})" >>  django/.build/.env
+	echo "AWS_SECRET_ACCESS_KEY=$$(heroku config:get AWS_SECRET_ACCESS_KEY -a ${APP_NAME})" >>  django/.build/.env
+	echo "SECRET_KEY=$$(heroku config:get SECRET_KEY -a ${APP_NAME})" >>  django/.build/.env
+	# this is only here for reciept purposes
+	echo "ASSET_VERSION=$$(git rev-parse HEAD)" >> django/.build/.env
 
 # There's a lot going on here:
 # 1. Generate a file called env.build for use during `docker build`
@@ -130,23 +146,50 @@ heroku.s3:
 # 3. Push the image to the heroku registry
 # 4. Run migrate on the newly deployed / active container
 .PHONY: heroku.deploy
-heroku.deploy: heroku.assets ## Deploy active git branch to a Heroku remote (see Usage)
-	bin/generate_build_env.sh heroku ${HEROKU_REMOTE}
-	docker build --build-arg ASSET_VERSION=$$(git rev-parse HEAD) \
-	. -f docker/heroku/Dockerfile -t registry.heroku.com/${HEROKU_SLUG}/web:latest
-	docker push registry.heroku.com/${HEROKU_SLUG}/web
-	heroku run python manage.py migrate
+heroku.deploy: heroku.assets buildenv
+	docker build \
+    --build-arg ASSET_VERSION=$$(git rev-parse HEAD) \
+    . -f docker/heroku/Dockerfile -t registry.heroku.com/${APP_NAME}/web:latest
+	docker push registry.heroku.com/${APP_NAME}/web
+	# heroku run ./manage.py makemigrations -a ${APP_NAME}
+	heroku run ./manage.py migrate -a ${APP_NAME}
+	heroku run ./manage.py clear_cache -a ${APP_NAME}
+
+# Exit if ENV_NAME does not match expected value
+.PHONY: heroku.checkenv
+heroku.checkenv:
+	@if [[ ! $$ENV_NAME == "dev" ]]; then \
+	if [[ ! $$ENV_NAME == "staging" ]]; then \
+	if [[ ! $$ENV_NAME == "prod" ]]; then \
+		echo "Invalid ENV_NAME=${ENV_NAME}, exiting..."; exit 1; \
+	fi \
+	fi \
+	fi
 
 # Build assets for the heroku deploy
 # NOTE: You should cancel any active local asset watches
 # 	and re-run them once the deploy is complete.
 .PHONY: heroku.assets
-heroku.assets:
+heroku.assets:  ## Build Heroku assets (takes ENV_NAME=<env-name>, see help)
 	-cd django/project/@static && \
 		IS_HEROKU=1 VERSION=$$(git rev-parse HEAD) \
-		USE_HTTPS_FOR_ASSETS=$$(heroku config:get USE_HTTPS_FOR_ASSETS -r ${HEROKU_REMOTE}) \
-		AWS_BUCKET_NAME=$$(heroku config:get AWS_BUCKET_NAME -r ${HEROKU_REMOTE}) \
+		USE_HTTPS_FOR_ASSETS=$$(heroku config:get USE_HTTPS_FOR_ASSETS -a ${APP_NAME}) \
+		AWS_BUCKET_NAME=$$(heroku config:get AWS_BUCKET_NAME -a ${APP_NAME}) \
 		npm run build
+
+.PHONY: heroku.shell
+heroku.shell: ## Get a session on the heroku container (takes ENV_NAME=<env-name>, see help)
+	docker run --rm -w /usr/app/django \
+		-v ${LOCATION}:/usr/app \
+		--net ${NAME}_default \
+		-e "DJANGO_SETTINGS_MODULE=app.config.settings.prod" \
+		-e "PYTHONPATH=/usr/app/django/project:/usr/app/django/project/vendor" \
+		-e "DEBUG=True" \
+		-e "AWS_BUCKET_NAME=$$(heroku config:get AWS_BUCKET_NAME -a ${APP_NAME})" \
+		-e "AWS_ACCESS_KEY_ID=$$(heroku config:get AWS_ACCESS_KEY_ID -a ${APP_NAME})" \
+		-e "AWS_SECRET_ACCESS_KEY=$$(heroku config:get AWS_SECRET_ACCESS_KEY -a ${APP_NAME})" \
+		-it dinopetrone/heroku:latest \
+		/bin/bash
 {% endif %}
 
 # Makefile Documentation
diff --git a/{{cookiecutter.project_slug}}/docker/heroku/Dockerfile b/{{cookiecutter.project_slug}}/docker/heroku/Dockerfile
--- a/{{cookiecutter.project_slug}}/docker/heroku/Dockerfile
+++ b/{{cookiecutter.project_slug}}/docker/heroku/Dockerfile
@@ -52,8 +52,8 @@ COPY ./django/ ./
 
 # Copy env.build to .env temporarily for collect static
 # NOTE: This overwrites any .env that may have been added from COPY above
-RUN [ -f ./env.build ] || echo "Could not fine env.build"
-RUN cp env.build .env
+RUN [ -f ./.build/.env ] || echo "Could not find ./.build/.env"
+COPY ./django/.build/.env .env
 
 # Run Collect Static
 # =====================================
@@ -85,4 +85,4 @@ USER heroku
 # CMD is required to run on Heroku
 # $PORT is set by Heroku
 
-CMD gunicorn app.config.wsgi --bind 0.0.0.0:$PORT -w 3 -k gevent
+CMD newrelic-admin run-program gunicorn app.config.wsgi --bind 0.0.0.0:$PORT -w 2 -k gevent
